### ISSUE TITLE
Change Rust Build Lessons to include Lesson Submission and report on Discord

### ISSUE THREAD

**Issue by nomadbitcoin** [w3b3d3v/web3-bootcamp-platform#166]

**Comment by nomadbitcoin** [comment]
Do you mean this Lesson submission text? 

![Image](https://github.com/w3b3d3v/web3-bootcamp-platform/assets/39248465/30adef99-ca47-41e4-bde1-44bd06cb4a9d)

Can you add more information about the Discord report? I'm not familiar with this step

**Comment by nomadbitcoin** [comment]
Wait I just saw you mentioning at #151 so what is this about?

**Comment by danicuki** [comment]
This data you refer is related to #151 

This issue is regarding to lesson content, in the .md file. We need to add a final thoughts in the lesson, explaining what the user needs to submit, like in this print (we call "Progress Report" in other builds:


![Image](https://github.com/w3b3d3v/web3-bootcamp-platform/assets/77552/22f4bea0-85e0-48f6-9ccd-30e9869dc138)
